TOP_50_AIRLINES = {
    "American Airlines": "american-airlines",
    "Delta Air Lines": "delta-air-lines",
    "United Airlines": "united-airlines",
    "Southwest Airlines": "southwest-airlines",
    "JetBlue Airways": "jetblue-airways",
    "Alaska Airlines": "alaska-airlines",
    "Air Canada": "air-canada",
    "WestJet": "westjet",
    "Aeromexico": "aeromexico",
    "LATAM Airlines": "latam-airlines",
    "Aerolineas Argentinas": "aerolineas-argentinas",
    "Avianca": "avianca",
    "Copa Airlines": "copa-airlines",
    "British Airways": "british-airways",
    "Virgin Atlantic": "virgin-atlantic-airways",
    "Lufthansa": "lufthansa",
    "Swiss International Air Lines": "swiss-international-air-lines",
    "Austrian Airlines": "austrian-airlines",
    "KLM Royal Dutch Airlines": "klm-royal-dutch-airlines",
    "Air France": "air-france",
    "Iberia": "iberia",
    "TAP Portugal": "tap-portugal",
    "Finnair": "finnair",
    "SAS Scandinavian Airlines": "sas-scandinavian-airlines",
    "Turkish Airlines": "turkish-airlines",
    "Ryanair": "ryanair",
    "easyJet": "easyjet",
    "Norwegian": "norwegian",
    "Emirates": "emirates-airline",
    "Qatar Airways": "qatar-airways",
    "Etihad Airways": "etihad-airways",
    "Oman Air": "oman-air",
    "Gulf Air": "gulf-air",
    "Saudia": "saudi-arabian-airlines",
    "Singapore Airlines": "singapore-airlines",
    "Cathay Pacific": "cathay-pacific-airways",
    "ANA All Nippon Airways": "ana-all-nippon-airways",
    "Japan Airlines": "japan-airlines",
    "Korean Air": "korean-air",
    "Asiana Airlines": "asiana-airlines",
    "EVA Air": "eva-air",
    "China Airlines": "china-airlines",
    "Air China": "air-china",
    "China Eastern Airlines": "china-eastern-airlines",
    "China Southern Airlines": "china-southern-airlines",
    "Hainan Airlines": "hainan-airlines",
    "Malaysia Airlines": "malaysia-airlines",
    "Thai Airways": "thai-airways",
    "Vietnam Airlines": "vietnam-airlines",
    "Air New Zealand": "air-new-zealand"
}